version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install selenium
      - pip install pytest
      - pip install allure-pytest
      # Download and install Chocolatey (a package manager for Windows)
      - powershell.exe -Command "Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))"

  pre_build:
    commands:
      # Install Chrome and Firefox using Chocolatey
      - powershell.exe -Command "choco install googlechrome -y"
      - |
        $chromePath = Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\chrome.exe' | Select-Object -ExpandProperty '(Default)'
        Write-Host "Chrome is installed at: $chromePath"
      #- powershell -Command "$chromePath = Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\chrome.exe' | Select-Object -ExpandProperty '(Default)'; Write-Host 'Chrome is installed at: ' + $chromePath"
      #- powershell.exe -Command "choco install firefox -y"
      #- powershell -command "(Get-Item 'C:\Program Files\Mozilla Firefox\firefox.exe').VersionInfo.FileVersion"



  build:
    commands:
      #- docker --version
      - "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe" https://www.amazon.com
      - cd TestAssessment/tests
      - pytest -m smoke --browser_name chrome

  post_build:
    commands:
      - allure generate --clean -o Reports allure-results

artifacts:
  files:
    - Reports/**/*