version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - pip install selenium
      - pip install pytest
      - pip install allure-pytest

  build:
    commands:
      - export FIREFOX_BIN=$(which firefox)
      - echo "Firefox Binary: $FIREFOX_BIN"
      - cd TestAssessment/tests
      - pytest -m smoke --browser_name firefox

  post_build:
    commands:
      - allure generate --clean -o Reports allure-results

artifacts:
  files:
    - Reports/**/*