version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install selenium
      - pip install pytest
      - pip install allure-pytest
      - yum install sudo
      - Y
      # Download and install Chocolatey (a package manager for Windows)
      #- powershell.exe -Command "Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))"

  pre_build:
    commands:
      # Install Chrome and Firefox using Chocolatey
      #- powershell.exe -Command "choco install googlechrome -y"
      #- powershell.exe -Command "choco install firefox -y"
      #- powershell -command "(Get-Item 'C:\Program Files\Mozilla Firefox\firefox.exe').VersionInfo.FileVersion"
      - sudo apt-get update
      - sudo apt-get install -y firefox


  build:
    commands:
      - docker --version
      - cd TestAssessment/tests
      - pytest -m smoke --browser_name firefox

  post_build:
    commands:
      - allure generate --clean -o Reports allure-results

artifacts:
  files:
    - Reports/**/*